/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AssetHierarchy } from "./AssetHierarchy";
import { AssetHierarchyCountArgs } from "./AssetHierarchyCountArgs";
import { AssetHierarchyFindManyArgs } from "./AssetHierarchyFindManyArgs";
import { AssetHierarchyFindUniqueArgs } from "./AssetHierarchyFindUniqueArgs";
import { CreateAssetHierarchyArgs } from "./CreateAssetHierarchyArgs";
import { UpdateAssetHierarchyArgs } from "./UpdateAssetHierarchyArgs";
import { DeleteAssetHierarchyArgs } from "./DeleteAssetHierarchyArgs";
import { AssetFindManyArgs } from "../../asset/base/AssetFindManyArgs";
import { Asset } from "../../asset/base/Asset";
import { HierarchyLevel } from "../../hierarchyLevel/base/HierarchyLevel";
import { AssetHierarchyService } from "../assetHierarchy.service";
@graphql.Resolver(() => AssetHierarchy)
export class AssetHierarchyResolverBase {
  constructor(protected readonly service: AssetHierarchyService) {}

  async _assetHierarchiesMeta(
    @graphql.Args() args: AssetHierarchyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AssetHierarchy])
  async assetHierarchies(
    @graphql.Args() args: AssetHierarchyFindManyArgs
  ): Promise<AssetHierarchy[]> {
    return this.service.assetHierarchies(args);
  }

  @graphql.Query(() => AssetHierarchy, { nullable: true })
  async assetHierarchy(
    @graphql.Args() args: AssetHierarchyFindUniqueArgs
  ): Promise<AssetHierarchy | null> {
    const result = await this.service.assetHierarchy(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AssetHierarchy)
  async createAssetHierarchy(
    @graphql.Args() args: CreateAssetHierarchyArgs
  ): Promise<AssetHierarchy> {
    return await this.service.createAssetHierarchy({
      ...args,
      data: {
        ...args.data,

        hierarchyLevel: args.data.hierarchyLevel
          ? {
              connect: args.data.hierarchyLevel,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => AssetHierarchy)
  async updateAssetHierarchy(
    @graphql.Args() args: UpdateAssetHierarchyArgs
  ): Promise<AssetHierarchy | null> {
    try {
      return await this.service.updateAssetHierarchy({
        ...args,
        data: {
          ...args.data,

          hierarchyLevel: args.data.hierarchyLevel
            ? {
                connect: args.data.hierarchyLevel,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AssetHierarchy)
  async deleteAssetHierarchy(
    @graphql.Args() args: DeleteAssetHierarchyArgs
  ): Promise<AssetHierarchy | null> {
    try {
      return await this.service.deleteAssetHierarchy(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Asset], { name: "assets" })
  async findAssets(
    @graphql.Parent() parent: AssetHierarchy,
    @graphql.Args() args: AssetFindManyArgs
  ): Promise<Asset[]> {
    const results = await this.service.findAssets(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => HierarchyLevel, {
    nullable: true,
    name: "hierarchyLevel",
  })
  async getHierarchyLevel(
    @graphql.Parent() parent: AssetHierarchy
  ): Promise<HierarchyLevel | null> {
    const result = await this.service.getHierarchyLevel(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
