/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RoleRightService } from "../roleRight.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RoleRightCreateInput } from "./RoleRightCreateInput";
import { RoleRight } from "./RoleRight";
import { RoleRightFindManyArgs } from "./RoleRightFindManyArgs";
import { RoleRightWhereUniqueInput } from "./RoleRightWhereUniqueInput";
import { RoleRightUpdateInput } from "./RoleRightUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RoleRightControllerBase {
  constructor(
    protected readonly service: RoleRightService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RoleRight })
  @nestAccessControl.UseRoles({
    resource: "RoleRight",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRoleRight(
    @common.Body() data: RoleRightCreateInput
  ): Promise<RoleRight> {
    return await this.service.createRoleRight({
      data: {
        ...data,

        role: data.role
          ? {
              connect: data.role,
            }
          : undefined,

        right: data.right
          ? {
              connect: data.right,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        role: {
          select: {
            id: true,
          },
        },

        right: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RoleRight] })
  @ApiNestedQuery(RoleRightFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RoleRight",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async roleRights(@common.Req() request: Request): Promise<RoleRight[]> {
    const args = plainToClass(RoleRightFindManyArgs, request.query);
    return this.service.roleRights({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        role: {
          select: {
            id: true,
          },
        },

        right: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RoleRight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RoleRight",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async roleRight(
    @common.Param() params: RoleRightWhereUniqueInput
  ): Promise<RoleRight | null> {
    const result = await this.service.roleRight({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        role: {
          select: {
            id: true,
          },
        },

        right: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RoleRight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RoleRight",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRoleRight(
    @common.Param() params: RoleRightWhereUniqueInput,
    @common.Body() data: RoleRightUpdateInput
  ): Promise<RoleRight | null> {
    try {
      return await this.service.updateRoleRight({
        where: params,
        data: {
          ...data,

          role: data.role
            ? {
                connect: data.role,
              }
            : undefined,

          right: data.right
            ? {
                connect: data.right,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          role: {
            select: {
              id: true,
            },
          },

          right: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RoleRight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RoleRight",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRoleRight(
    @common.Param() params: RoleRightWhereUniqueInput
  ): Promise<RoleRight | null> {
    try {
      return await this.service.deleteRoleRight({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          role: {
            select: {
              id: true,
            },
          },

          right: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
